AD2-107:
  hostname: 10.5.112.105
  password: AD2@IITH2022
  username: iith
AD2-108:
  hostname: 10.5.112.106
  password: AD2@IITH2022
  username: iith
AD2-208:
  hostname: 10.5.112.107
  password: AD2@IITH2022
  username: iith
AD2-317:
  hostname: 10.5.112.108
  password: AD2@IITH2022
  username: iith
AD2-318:
  hostname: 10.5.112.109
  password: AD2@IITH2022
  username: iith
AD2-319:
  hostname: 10.5.112.110
  password: AD2@IITH2022
  username: iith
AD2-320:
  hostname: 10.5.112.111
  password: AD2@IITH2022
  username: iith
AD2-411:
  hostname: 10.5.112.112
  password: AD2@IITH2022
  username: iith
AD2-Dist-SW:
  hostname: 192.168.41.134
  password: AD2@IITH2022
  username: iith
AD2-SHAFT-A-2F:
  hostname: 10.5.112.101
  password: AD2@IITH2022
  username: iith
AD2-SHAFT-B-2F:
  hostname: 10.5.112.102
  password: AD2@IITH2022
  username: iith
AD2-SHAFT-C-3F-R1:
  hostname: 10.5.112.103
  password: AD2@IITH2022
  username: iith
AD2-SHAFT-C-3F-R2:
  hostname: 10.5.112.104
  password: AD2@IITH2022
  username: iith
AD3-Dist-SW:
  hostname: 192.168.41.138
  password: AD3@IITH2022
  username: iith
AD3-MA321:
  hostname: 10.5.116.108
  password: AD3@IITH2022
  username: iith
AD3-SHAFT-A-2F:
  hostname: 10.5.116.101
  password: AD3@IITH2022
  username: iith
AD3-SHAFT-B-2F:
  hostname: 10.5.116.102
  password: AD3@IITH2022
  username: iith
AD3-SHAFT-B-2F-LA205-RACK:
  hostname: 10.5.116.106
  password: AD3@IITH2022
  username: iith
AD3-SHAFT-B-4F:
  hostname: 10.5.116.103
  password: AD3@IITH2022
  username: iith
AD3-SHAFT-C-1F:
  hostname: 10.5.116.104
  password: AD3@IITH2022
  username: iith
AD3-SHAFT-C-4F:
  hostname: 10.5.116.105
  password: AD3@IITH2022
  username: iith
Admin-LGF-Dist-SW:
  hostname: 192.168.41.142
  password: ADMIN@IITH2022
  username: iith
Admin-Shaft_A-1F:
  hostname: 10.5.120.103
  password: ADMIN@IITH2022
  username: iith
Admin-Shaft_A-2F:
  hostname: 10.5.120.104
  password: ADMIN@IITH2022
  username: iith
Admin-Shaft_A-3F:
  hostname: 10.5.120.105
  password: ADMIN@IITH2022
  username: iith
Admin-Shaft_A-4F:
  hostname: 10.5.120.106
  password: ADMIN@IITH2022
  username: iith
Admin-Shaft_A-5F:
  hostname: 10.5.120.107
  password: ADMIN@IITH2022
  username: iith
Admin-Shaft_A-GF:
  hostname: 10.5.120.102
  password: ADMIN@IITH2022
  username: iith
Admin-Shaft_A-LGF:
  hostname: 10.5.120.101
  password: ADMIN@IITH2022
  username: iith
Admin-Shaft_B-1F:
  hostname: 10.5.120.109
  password: ADMIN@IITH2022
  username: iith
Admin-Shaft_B-2F:
  hostname: 10.5.120.110
  password: ADMIN@IITH2022
  username: iith
Admin-Shaft_B-3F:
  hostname: 10.5.120.111
  password: ADMIN@IITH2022
  username: iith
Admin-Shaft_B-4F:
  hostname: 10.5.120.112
  password: ADMIN@IITH2022
  username: iith
Admin-Shaft_B-5F(Dir):
  hostname: 10.5.120.113
  password: ADMIN@IITH2022
  username: iith
Admin-Shaft_B-GF:
  hostname: 10.5.120.108
  password: ADMIN@IITH2022
  username: iith
BHJ-A-3F-SW:
  hostname: 10.5.48.12
  password: HSTLJ@IITH2022
  username: iith
BHJ-A-6F-SW:
  hostname: 10.5.48.13
  password: HSTLJ@IITH2022
  username: iith
BHJ-A-9F-SW:
  hostname: 10.5.48.14
  password: HSTLJ@IITH2022
  username: iith
BHJ-A-GF-SW:
  hostname: 10.5.48.11
  password: HSTLJ@IITH2022
  username: iith
BHJ-B-3F-SW:
  hostname: 10.5.48.17
  password: HSTLJ@IITH2022
  username: iith
BHJ-B-6F-SW:
  hostname: 10.5.48.18
  password: HSTLJ@IITH2022
  username: iith
BHJ-B-9F-SW:
  hostname: 10.5.48.19
  password: HSTLJ@IITH2022
  username: iith
BHJ-B-GF-SW:
  hostname: 10.5.48.16
  password: HSTLJ@IITH2022
  username: iith
BHK-A-3F-SW:
  hostname: 10.5.48.22
  password: HSTLK@IITH2022
  username: iith
BHK-A-6F-SW:
  hostname: 10.5.48.23
  password: HSTLK@IITH2022
  username: iith
BHK-A-9F-SW:
  hostname: 10.5.48.24
  password: HSTLK@IITH2022
  username: iith
BHK-A-GF-SW:
  hostname: 10.5.48.21
  password: HSTLK@IITH2022
  username: iith
BHK-B-3F-SW:
  hostname: 10.5.48.27
  password: HSTLK@IITH2022
  username: iith
BHK-B-6F-SW:
  hostname: 10.5.48.28
  password: HSTLK@IITH2022
  username: iith
BHK-B-9F-SW:
  hostname: 10.5.48.29
  password: HSTLK@IITH2022
  username: iith
BHK-B-GF-SW:
  hostname: 10.5.48.26
  password: HSTLK@IITH2022
  username: iith
BHL-A-3F-SW:
  hostname: 10.5.48.32
  password: HSTLL@IITH2022
  username: iith
BHL-A-6F-SW:
  hostname: 10.5.48.33
  password: HSTLL@IITH2022
  username: iith
BHL-A-9F-SW:
  hostname: 10.5.48.34
  password: HSTLL@IITH2022
  username: iith
BHL-A-GF-SW:
  hostname: 10.5.48.31
  password: HSTLL@IITH2022
  username: iith
BHL-B-3F-SW:
  hostname: 10.5.48.37
  password: HSTLL@IITH2022
  username: iith
BHL-B-6F-SW:
  hostname: 10.5.48.38
  password: HSTLL@IITH2022
  username: iith
BHL-B-9F-SW:
  hostname: 10.5.48.39
  password: HSTLL@IITH2022
  username: iith
BHL-B-GF-SW:
  hostname: 10.5.48.36
  password: HSTLL@IITH2022
  username: iith
BHM-A-3F-SW:
  hostname: 10.5.48.42
  password: HSTLM@IITH2022
  username: iith
BHM-A-6F-SW:
  hostname: 10.5.48.43
  password: HSTLM@IITH2022
  username: iith
BHM-A-9F-SW:
  hostname: 10.5.48.44
  password: HSTLM@IITH2022
  username: iith
BHM-A-GF-SW:
  hostname: 10.5.48.41
  password: HSTLM@IITH2022
  username: iith
BHM-B-3F-SW:
  hostname: 10.5.48.47
  password: HSTLM@IITH2022
  username: iith
BHM-B-6F-SW:
  hostname: 10.5.48.48
  password: HSTLM@IITH2022
  username: iith
BHM-B-9F-SW:
  hostname: 10.5.48.49
  password: HSTLM@IITH2022
  username: iith
BHM-B-GF-Dist-SW:
  hostname: 192.168.41.150
  password: HSTLM@IITH2022
  username: iith
BHM-B-GF-SW:
  hostname: 10.5.48.46
  password: HSTLM@IITH2022
  username: iith
BHN-A-3F-SW:
  hostname: 10.5.48.52
  password: HSTLN@IITH2022
  username: iith
BHN-A-6F-SW:
  hostname: 10.5.48.53
  password: HSTLN@IITH2022
  username: iith
BHN-A-9F-SW:
  hostname: 10.5.48.54
  password: HSTLN@IITH2022
  username: iith
BHN-A-GF-SW:
  hostname: 10.5.48.51
  password: HSTLN@IITH2022
  username: iith
BHN-B-3F-SW:
  hostname: 10.5.48.57
  password: HSTLN@IITH2022
  username: iith
BHN-B-6F-SW:
  hostname: 10.5.48.58
  password: HSTLN@IITH2022
  username: iith
BHN-B-9F-SW:
  hostname: 10.5.48.59
  password: HSTLN@IITH2022
  username: iith
BHN-B-GF-SW:
  hostname: 10.5.48.56
  password: HSTLN@IITH2022
  username: iith
BHP-A-3F-SW:
  hostname: 10.5.48.62
  password: HSTLP@IITH2022
  username: iith
BHP-A-6F-SW:
  hostname: 10.5.48.63
  password: HSTLP@IITH2022
  username: iith
BHP-A-9F-SW:
  hostname: 10.5.48.64
  password: HSTLP@IITH2022
  username: iith
BHP-A-GF-SW:
  hostname: 10.5.48.61
  password: HSTLP@IITH2022
  username: iith
BHP-B-3F-SW:
  hostname: 10.5.48.67
  password: HSTLP@IITH2022
  username: iith
BHP-B-6F-SW:
  hostname: 10.5.48.68
  password: HSTLP@IITH2022
  username: iith
BHP-B-9F-SW:
  hostname: 10.5.48.69
  password: HSTLP@IITH2022
  username: iith
BHP-B-GF-SW:
  hostname: 10.5.48.66
  password: HSTLP@IITH2022
  username: iith
BHP1-A-3F-SW:
  hostname: 10.5.48.72
  password: HSTLP1@IITH2022
  username: iith
BHP1-A-6F-SW:
  hostname: 10.5.48.73
  password: HSTLP1@IITH2022
  username: iith
BHP1-A-9F-SW:
  hostname: 10.5.48.74
  password: HSTLP1@IITH2022
  username: iith
BHP1-A-GF-SW:
  hostname: 10.5.48.71
  password: HSTLP1@IITH2022
  username: iith
BHP1-B-3F-SW:
  hostname: 10.5.48.77
  password: HSTLP1@IITH2022
  username: iith
BHP1-B-6F-SW:
  hostname: 10.5.48.78
  password: HSTLP1@IITH2022
  username: iith
BHP1-B-9F-SW:
  hostname: 10.5.48.79
  password: HSTLP1@IITH2022
  username: iith
BHP1-B-GF-SW:
  hostname: 10.5.48.76
  password: HSTLP1@IITH2022
  username: iith
BHQ-A-3F-SW:
  hostname: 10.5.48.82
  password: HSTLQ@IITH2022
  username: iith
BHQ-A-6F-SW:
  hostname: 10.5.48.83
  password: HSTLQ@IITH2022
  username: iith
BHQ-A-9F-SW:
  hostname: 10.5.48.84
  password: HSTLQ@IITH2022
  username: iith
BHQ-A-GF-SW:
  hostname: 10.5.48.81
  password: HSTLQ@IITH2022
  username: iith
BHQ-B-3F-SW:
  hostname: 10.5.48.87
  password: HSTLQ@IITH2022
  username: iith
BHQ-B-6F-SW:
  hostname: 10.5.48.88
  password: HSTLQ@IITH2022
  username: iith
BHQ-B-9F-SW:
  hostname: 10.5.48.89
  password: HSTLQ@IITH2022
  username: iith
BHQ-B-GF-SW:
  hostname: 10.5.48.86
  password: HSTLQ@IITH2022
  username: iith
BM-1F:
  hostname: 10.4.104.106
  password: BTBM@IITH2022
  username: iith
BM-2F:
  hostname: 10.4.104.107
  password: BTBM@IITH2022
  username: iith
BM-3F:
  hostname: 10.4.104.108
  password: BTBM@IITH2022
  username: iith
BM-GF:
  hostname: 10.4.104.105
  password: BTBM@IITH2022
  username: iith
BT-1F:
  hostname: 10.4.104.100
  password: BTBM@IITH2022
  username: iith
BT-2F:
  hostname: 10.4.104.102
  password: BTBM@IITH2022
  username: iith
BT-3F:
  hostname: 10.4.104.103
  password: BTBM@IITH2022
  username: iith
BT-Dist-SW:
  hostname: 192.168.41.86
  password: BTBM@IITH2022
  username: iith
BT-GF:
  hostname: 10.4.104.101
  password: BTBM@IITH2022
  username: iith
BTBM-4F:
  hostname: 10.4.104.104
  password: BTBM@IITH2022
  username: iith
CAMPUS-SCHOOL-2F:
  hostname: 10.5.100.96
  password: CS@IITH2022
  username: iith
CAMPUS-SCHOOL-GF:
  hostname: 10.5.100.95
  password: CS@IITH2022
  username: iith
CC-Dist-SW:
  hostname: 192.168.41.110
  password: CC@IITH2022
  username: iith
CC-R1-00:
  hostname: 10.4.124.107
  password: CC@IITH2022
  username: iith
CC-R1-02:
  hostname: 10.4.124.109
  password: CC@IITH2022
  username: iith
CC-R2-00:
  hostname: 10.4.124.105
  password: CC@IITH2022
  username: iith
CC-R2-02:
  hostname: 10.4.124.110
  password: CC@IITH2022
  username: iith
CC-R3-00:
  hostname: 10.4.124.103
  password: CC@IITH2022
  username: iith
CC-R3-02:
  hostname: 10.4.124.111
  password: CC@IITH2022
  username: iith
CC-R4-00:
  hostname: 10.4.124.104
  password: CC@IITH2022
  username: iith
CC-R5-00 ( Behind Auditorium 1):
  hostname: 10.4.124.102
  password: CC@IITH2022
  username: iith
CC-R6-00:
  hostname: 10.4.124.106
  password: CC@IITH2022
  username: iith
CC-R7-00:
  hostname: 10.4.124.101
  password: CC@IITH2022
  username: iith
CHY-00-ACC:
  hostname: 10.4.108.102
  password: CHY@IITH2022
  username: iith
CHY-01-ACC:
  hostname: 10.4.108.101
  password: CHY@IITH2022
  username: iith
CHY-02-ACC:
  hostname: 10.4.108.103
  password: CHY@IITH2022
  username: iith
CHY-03-ACC:
  hostname: 10.4.108.104
  password: CHY@IITH2022
  username: iith
CHY-04-ACC:
  hostname: 10.4.108.105
  password: CHY@IITH2022
  username: iith
CHY-05-ACC:
  hostname: 10.4.108.106
  password: CHY@IITH2022
  username: iith
CHY-Dist-SW:
  hostname: 192.168.41.90
  password: CHY@IITH2022
  username: iith
CoreLab-1F:
  hostname: 10.5.104.102
  password: CORELAB@IITH2022
  username: iith
CoreLab-2F:
  hostname: 10.5.104.103
  password: CORELAB@IITH2022
  username: iith
CoreLab-GF:
  hostname: 10.5.104.101
  password: CORELAB@IITH2022
  username: iith
Corelab-Dist-SW:
  hostname: 192.168.41.126
  password: CORELAB@IITH2022
  username: iith
DH-Dist-SW:
  hostname: 192.168.41.122
  password: DH@IITH2022
  username: iith
DoD-Dist-SW:
  hostname: 192.168.41.146
  password: DOD@IITH2022
  username: iith
DoD-Z1-GF:
  hostname: 10.5.124.101
  password: DOD@IITH2022
  username: iith
DoD-Z2-GF:
  hostname: 10.5.124.102
  password: DOD@IITH2022
  username: iith
DoD-Z3-GF:
  hostname: 10.5.124.103
  password: DOD@IITH2022
  username: iith
DoD-Z5-1F:
  hostname: 10.5.124.104
  password: DOD@IITH2022
  username: iith
DoD-Z6-2F:
  hostname: 10.5.124.105
  password: DOD@IITH2022
  username: iith
DoD-Z7-1F:
  hostname: 10.5.124.106
  password: DOD@IITH2022
  username: iith
DoD-Z8-2F:
  hostname: 10.5.124.107
  password: DOD@IITH2022
  username: iith
DoD-Z9-3F:
  hostname: 10.5.124.108
  password: DOD@IITH2022
  username: iith
Hospital-1F:
  hostname: 192.168.9.140
  password: HCF@IITH2022
  username: iith
IGH- R1-1F:
  hostname: 10.4.128.107
  password: IGH@IITH2022
  username: iith
IGH- R1-2F:
  hostname: 10.4.128.108
  password: IGH@IITH2022
  username: iith
IGH- R1-3F:
  hostname: 10.4.128.109
  password: IGH@IITH2022
  username: iith
IGH- R1-4F:
  hostname: 10.4.128.110
  password: IGH@IITH2022
  username: iith
IGH- R1-5F:
  hostname: 10.4.128.111
  password: IGH@IITH2022
  username: iith
IGH- R1-GF:
  hostname: 10.4.128.106
  password: IGH@IITH2022
  username: iith
IGH- R2-1F:
  hostname: 10.4.128.113
  password: IGH@IITH2022
  username: iith
IGH- R2-2F:
  hostname: 10.4.128.114
  password: IGH@IITH2022
  username: iith
IGH- R2-3F:
  hostname: 10.4.128.115
  password: IGH@IITH2022
  username: iith
IGH- R2-4F:
  hostname: 10.4.128.116
  password: IGH@IITH2022
  username: iith
IGH- R2-5F:
  hostname: 10.4.128.117
  password: IGH@IITH2022
  username: iith
IGH- R2-GF:
  hostname: 10.4.128.112
  password: IGH@IITH2022
  username: iith
IGH- R3-1F:
  hostname: 10.4.128.100
  password: IGH@IITH2022
  username: iith
IGH- R3-2F:
  hostname: 10.4.128.102
  password: IGH@IITH2022
  username: iith
IGH- R3-3F:
  hostname: 10.4.128.103
  password: IGH@IITH2022
  username: iith
IGH- R3-4F:
  hostname: 10.4.128.104
  password: IGH@IITH2022
  username: iith
IGH- R3-GF:
  hostname: 10.4.128.101
  password: IGH@IITH2022
  username: iith
IGH- R4-1F:
  hostname: 10.4.128.119
  password: IGH@IITH2022
  username: iith
IGH- R4-2F:
  hostname: 10.4.128.120
  password: IGH@IITH2022
  username: iith
IGH- R4-3F:
  hostname: 10.4.128.121
  password: IGH@IITH2022
  username: iith
IGH- R4-4F:
  hostname: 10.4.128.122
  password: IGH@IITH2022
  username: iith
IGH- R4-GF:
  hostname: 10.4.128.118
  password: IGH@IITH2022
  username: iith
IGH-Dist-SW:
  hostname: 192.168.41.114
  password: IGH@IITH2022
  username: iith
KNC-Dist-SW:
  hostname: 192.168.41.106
  password: KNC@IITH2022
  username: iith
KNC-R1-00:
  hostname: 10.4.120.101
  password: KNC@IITH2022
  username: iith
KNC-R1-01:
  hostname: 10.4.120.102
  password: KNC@IITH2022
  username: iith
KNC-R1-02:
  hostname: 10.4.120.103
  password: KNC@IITH2022
  username: iith
KNC-R1-03:
  hostname: 10.4.120.104
  password: KNC@IITH2022
  username: iith
KNC-R2-00:
  hostname: 10.4.120.105
  password: KNC@IITH2022
  username: iith
KNC-R2-02:
  hostname: 10.4.120.106
  password: KNC@IITH2022
  username: iith
KNC-R2-03:
  hostname: 10.4.120.107
  password: KNC@IITH2022
  username: iith
LH-5-800Seater-AVRoom:
  hostname: 10.5.108.106
  password: LH@IITH2023
  username: iith
LH-Dist-SW(room no. 7):
  hostname: 192.168.41.130
  password: LH@IITH2022
  username: iith
LH-Part 1-LGF (room no. 7):
  hostname: 10.5.108.101
  password: LH@IITH2022
  username: iith
LH-Part 1-UGF(room no. 14):
  hostname: 10.5.108.102
  password: LH@IITH2022
  username: iith
LH-Part 3-UGF-Sw1(room no. 13):
  hostname: 10.5.108.103
  password: LH@IITH2022
  username: iith
LH-Part 3-UGF-Sw2(room no. 13):
  hostname: 10.5.108.104
  password: LH@IITH2022
  username: iith
LH-Part 5-UGF (room no. 12):
  hostname: 10.5.108.105
  password: LH@IITH2022
  username: iith
MSH-North-SW:
  hostname: 10.5.100.106
  password: MSH@IITH2022
  username: iith
MSH-South-SW:
  hostname: 10.5.100.107
  password: MSH@IITH2022
  username: iith
MSME-1F-SW:
  hostname: 10.4.100.101
  password: MSME@IITH2022
  username: iith
MSME-2F-SW:
  hostname: 10.4.100.103
  password: MSME@IITH2022
  username: iith
MSME-3F-SW:
  hostname: 10.4.100.104
  password: MSME@IITH2022
  username: iith
MSME-4F-SW:
  hostname: 10.4.100.105
  password: MSME@IITH2022
  username: iith
MSME-Dist-SW:
  hostname: 192.168.41.182
  password: MSME@IITH2022
  username: iith
MSME-GF-SW:
  hostname: 10.4.100.102
  password: MSME@IITH2022
  username: iith
NewDH-SW:
  hostname: 10.5.100.101
  password: DH@IITH2022
  username: iith
RCC-Dist-SW:
  hostname: 192.168.41.94
  password: RCC@IITH2022
  username: iith
RCC-R1-1F:
  hostname: 10.4.112.101
  password: RCC@IITH2022
  username: iith
RCC-R1-2F:
  hostname: 10.4.112.102
  password: RCC@IITH2022
  username: iith
RCC-R1-3F:
  hostname: 10.4.112.103
  password: RCC@IITH2022
  username: iith
RCC-R1-4F:
  hostname: 10.4.112.110
  password: RCC@IITH2022
  username: iith
RCC-R1-GF:
  hostname: 10.4.112.100
  password: RCC@IITH2022
  username: iith
RCC-R2-2F:
  hostname: 10.4.112.106
  password: RCC@IITH2022
  username: iith
RCC-R2-3F:
  hostname: 10.4.112.107
  password: RCC@IITH2022
  username: iith
RCC-R2-4F:
  hostname: 10.4.112.109
  password: RCC@IITH2022
  username: iith
RCC-R2-GF:
  hostname: 10.4.112.105
  password: RCC@IITH2022
  username: iith
SNCC-1F-R1:
  hostname: 10.4.132.107
  password: SNCC@IITH2022
  username: iith
SNCC-1F-R2:
  hostname: 10.4.132.108
  password: SNCC@IITH2022
  username: iith
SNCC-1F-R3(near swimming pool):
  hostname: 10.4.132.109
  password: SNCC@IITH2022
  username: iith
SNCC-Dist-SW:
  hostname: 192.168.41.118
  password: SNCC@IITH2022
  username: iith
SNCC-GF-R1:
  hostname: 10.4.132.101
  password: SNCC@IITH2022
  username: iith
SNCC-GF-R2:
  hostname: 10.4.132.102
  password: SNCC@IITH2022
  username: iith
SNCC-GF-R3:
  hostname: 10.4.132.104
  password: SNCC@IITH2022
  username: iith
SNCC-GF-R4:
  hostname: 10.4.132.105
  password: SNCC@IITH2022
  username: iith
SNCC-GF-R5:
  hostname: 10.4.132.106
  password: SNCC@IITH2022
  username: iith
SNCC-GF-R6(near OAT):
  hostname: 10.4.132.103
  password: SNCC@IITH2022
  username: iith
TIP-A wing-1F:
  hostname: 10.4.136.101
  password: TIP@IITH2022
  username: iith
TIP-A wing-2F:
  hostname: 10.4.136.102
  password: TIP@IITH2022
  username: iith
TIP-A wing-3F:
  hostname: 10.4.136.103
  password: TIP@IITH2022
  username: iith
TIP-A wing-4F:
  hostname: 10.4.136.104
  password: TIP@IITH2022
  username: iith
TIP-A wing-GF:
  hostname: 10.4.136.100
  password: TIP@IITH2022
  username: iith
TIP-B wing-1F:
  hostname: 10.4.136.106
  password: TIP@IITH2022
  username: iith
TIP-B wing-2F:
  hostname: 10.4.136.107
  password: TIP@IITH2022
  username: iith
TIP-B wing-3F:
  hostname: 10.4.136.108
  password: TIP@IITH2022
  username: iith
TIP-B wing-4F:
  hostname: 10.4.136.109
  password: TIP@IITH2022
  username: iith
TIP-B wing-5F:
  hostname: 10.4.136.110
  password: TIP@IITH2022
  username: iith
TIP-B wing-GF:
  hostname: 10.4.136.105
  password: TIP@IITH2022
  username: iith
TIP-Dist-SW:
  hostname: 192.168.41.98
  password: TIP@IITH2022
  username: iith
