AA-01-Steel-PoESw:
  groups:
  - aruba_os
  hostname: 192.168.95.23
  password: N@m@ste!
  username: iith
AA-01-Steel-Sw1:
  groups:
  - aruba_os
  hostname: 192.168.95.9
  password: N@m@ste!
  username: iith
AA-02-R3-DIRsw:
  groups:
  - aruba_os
  hostname: 192.168.9.56
  password: N@m@ste!
  username: iith
Pch1-Flr-2-Wing-A-Sw1:
  groups:
  - aruba_os
  hostname: 10.1.128.11
  password: Pch1@2023
  username: iith

