---

Sarabhai-Distribution-SW:
  groups:
  - cisco
  hostname: 10.5.48.1
  password: HSTLM@IITH2022
  username: iith

R1:
  groups:
  - cisco
  hostname: 10.5.48.89
  password: HSTLQ@IITH2022
  username: iith