IGH- R1-1F:
  groups:
  - cisco
  hostname: 10.4.128.107
  password: IGH@IITH2022
  username: iith
IGH- R1-2F:
  groups:
  - cisco
  hostname: 10.4.128.108
  password: IGH@IITH2022
  username: iith
IGH- R1-3F:
  groups:
  - cisco
  hostname: 10.4.128.109
  password: IGH@IITH2022
  username: iith
IGH- R1-4F:
  groups:
  - cisco
  hostname: 10.4.128.110
  password: IGH@IITH2022
  username: iith
IGH- R1-5F:
  groups:
  - cisco
  hostname: 10.4.128.111
  password: IGH@IITH2022
  username: iith
IGH- R1-GF:
  groups:
  - cisco
  hostname: 10.4.128.106
  password: IGH@IITH2022
  username: iith
IGH- R2-1F:
  groups:
  - cisco
  hostname: 10.4.128.113
  password: IGH@IITH2022
  username: iith
IGH- R2-2F:
  groups:
  - cisco
  hostname: 10.4.128.114
  password: IGH@IITH2022
  username: iith
IGH- R2-3F:
  groups:
  - cisco
  hostname: 10.4.128.115
  password: IGH@IITH2022
  username: iith
IGH- R2-4F:
  groups:
  - cisco
  hostname: 10.4.128.116
  password: IGH@IITH2022
  username: iith
IGH- R2-5F:
  groups:
  - cisco
  hostname: 10.4.128.117
  password: IGH@IITH2022
  username: iith
IGH- R2-GF:
  groups:
  - cisco
  hostname: 10.4.128.112
  password: IGH@IITH2022
  username: iith
IGH- R3-1F:
  groups:
  - cisco
  hostname: 10.4.128.100
  password: IGH@IITH2022
  username: iith
IGH- R3-2F:
  groups:
  - cisco
  hostname: 10.4.128.102
  password: IGH@IITH2022
  username: iith
IGH- R3-3F:
  groups:
  - cisco
  hostname: 10.4.128.103
  password: IGH@IITH2022
  username: iith
IGH- R3-4F:
  groups:
  - cisco
  hostname: 10.4.128.104
  password: IGH@IITH2022
  username: iith
IGH- R3-GF:
  groups:
  - cisco
  hostname: 10.4.128.101
  password: IGH@IITH2022
  username: iith
IGH- R4-1F:
  groups:
  - cisco
  hostname: 10.4.128.119
  password: IGH@IITH2022
  username: iith
IGH- R4-2F:
  groups:
  - cisco
  hostname: 10.4.128.120
  password: IGH@IITH2022
  username: iith
IGH- R4-3F:
  groups:
  - cisco
  hostname: 10.4.128.121
  password: IGH@IITH2022
  username: iith
IGH- R4-4F:
  groups:
  - cisco
  hostname: 10.4.128.122
  password: IGH@IITH2022
  username: iith
IGH- R4-GF:
  groups:
  - cisco
  hostname: 10.4.128.118
  password: IGH@IITH2022
  username: iith
IGH-Dist:
  groups:
  - cisco
  hostname: 10.4.128.1
  password: IGH@IITH2022
  username: iith
